// resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.svelte
<script>

// /home/dorn/Dev/yatodo-inertia/resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.svelte

    import { t } from 'svelte-i18n';

    import { useForm, page } from '@inertiajs/svelte'; // Ensure proper import

    //
    import FormSection from '@components/Forms/FormSection.svelte';
    import ActionMessage from '@components/Forms/ActionMessage.svelte';

    //
    import Button from '@components/UI/Buttons/Button.svelte';
    import FieldText from '@components/Fields/Text.svelte';

    let photoInput;
    let photoPreview = null;
    let photoName = null;
    let verificationLinkSent = false;

    //$: user = $page?.props?.user; // Use optional chaining to prevent errors
    $: user = $page?.props?.auth?.user || {};

    // Reactive form object initialization
    $: form = useForm({
        name: user.name || '',  // Reactively update when user changes
        email: user.email || '',
        photo: null,
    })

    function updateProfileInformation() {
        if (photoInput?.files[0]) {
            form.photo = photoInput.files[0];
        }
        $form.put(route('user-profile-information.update'), {
            errorBag: 'updateProfileInformation',
            preserveScroll: true,
        });
    }

    function selectNewPhoto() {
        photoInput.click();
    }

    function updatePhotoPreview() {
        const file = photoInput.files[0];
        if (file) {
            photoName = file.name;
            const reader = new FileReader();
            reader.onload = (e) => (photoPreview = e.target.result);
            reader.readAsDataURL(file);
        }
    }

    function deletePhoto() {
        form.delete(route('current-user-photo.destroy'), {
            preserveScroll: true,
            onSuccess: () => (photoPreview = null),
        });
    }

    function sendEmailVerification() {
        verificationLinkSent = true;
    }
</script>

<FormSection on:submit={updateProfileInformation}>
    <div slot="title">{$t('Profile Information')}</div>
    <div slot="description">{$t('Update your account\'s profile information and email address.')}</div>
    <div slot="form">
        {#if $page.props.jetstream.managesProfilePhotos}
            <input
                type="file"
                class="hidden"
                bind:this={photoInput}
                on:change={updatePhotoPreview}
            />

            {#if !photoPreview}
                <img src={user?.profile_photo_url} alt={user?.name} class="rounded-full h-20 w-20 object-cover" />
            {/if}

            {#if photoPreview}
                <div class="rounded-full w-20 h-20 bg-cover bg-center"
                    style="background-image: url('{photoPreview}');">
                </div>
            {/if}

            <button type="button" on:click|preventDefault={selectNewPhoto}>
                {$t('Select A New Photo')}
            </button>

            {#if user?.profile_photo_path}
                <button type="button" on:click|preventDefault={deletePhoto}>
                    {$t('Remove Photo')}
                </button>
            {/if}
        {/if}


        <FieldText 
            form={$form} 
            name="name" 
            id="name" 
            label="{$t('Name')}" 
        />

        <FieldText 
            form={$form} 
            name="email" 
            id="email" 
            label="{$t('email')}" 
        />  

    </div>

    <div slot="actions">
        <ActionMessage on={form.recentlySuccessful}>{$t('Saved')}</ActionMessage>

        <Button
            cssClass="btn-outline-primary"
            type="submit"
            disabled={form.processing}
            aria-label="Save Profile"
        >
            {$t('Save')}
        </Button>
    </div>
</FormSection>




<!-- 

<div class="form-floating mb-3">
<TextInput id="name" type="text" bind:value={form.name} required autocomplete="name" />
<InputLabel for="name" value="Name" />
<InputError message={form.errors.name} class="mt-2" />
</div>

<div class="form-floating mb-3">
<TextInput id="email" type="email" bind:value={form.email} required autocomplete="username" />
<InputLabel for="email" value="Email" />
<InputError message={form.errors.email} class="mt-2" />

{#if page.props.jetstream.hasEmailVerification && !user.email_verified_at}
    <p class="text-sm mt-2 dark:text-white">
        Your email address is unverified.
        <button
            type="button"
            class="underline text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:focus:ring-offset-gray-800"
            on:click|preventDefault={sendEmailVerification}
        >
            Click here to re-send the verification email.
        </button>
    </p>

    {#if verificationLinkSent}
        <p class="mt-2 font-medium text-sm text-green-600 dark:text-green-400">
            A new verification link has been sent to your email address.
        </p>
    {/if}
{/if}
</div> -->

// resources/js/Pages/Profile/Partials/____UpdateProfileInformationForm.vue
<script setup>
import { ref } from 'vue';
import { Link, router, useForm } from '@inertiajs/vue3';
import ActionMessage from '@/Components/__ActionMessage.vue';
import FormSection from '@/Components/__FormSection.vue';
import InputError from '@/Components/__InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import SecondaryButton from '@/Components/SecondaryButton.vue';
import TextInput from '@/Components/TextInput.vue';

const props = defineProps({
    user: Object,
});

const form = useForm({
    _method: 'PUT',
    name: props.user.name,
    email: props.user.email,
    photo: null,
});

const verificationLinkSent = ref(null);
const photoPreview = ref(null);
const photoInput = ref(null);

const updateProfileInformation = () => {
    if (photoInput.value) {
        form.photo = photoInput.value.files[0];
    }

    form.post(route('user-profile-information.update'), {
        errorBag: 'updateProfileInformation',
        preserveScroll: true,
        onSuccess: () => clearPhotoFileInput(),
    });
};

const sendEmailVerification = () => {
    verificationLinkSent.value = true;
};

const selectNewPhoto = () => {
    photoInput.value.click();
};

const updatePhotoPreview = () => {
    const photo = photoInput.value.files[0];

    if (! photo) return;

    const reader = new FileReader();

    reader.onload = (e) => {
        photoPreview.value = e.target.result;
    };

    reader.readAsDataURL(photo);
};

const deletePhoto = () => {
    router.delete(route('current-user-photo.destroy'), {
        preserveScroll: true,
        onSuccess: () => {
            photoPreview.value = null;
            clearPhotoFileInput();
        },
    });
};

const clearPhotoFileInput = () => {
    if (photoInput.value?.value) {
        photoInput.value.value = null;
    }
};
</script>

<template>
    <FormSection @submitted="updateProfileInformation">
        <template #title>
            Profile Information
        </template>

        <template #description>
            Update your account's profile information and email address.
        </template>

        <template #form>
            <!-- Profile Photo -->
            <div v-if="$page.props.jetstream.managesProfilePhotos" class="col-span-6 sm:col-span-4">
                <!-- Profile Photo File Input -->
                <input
                    id="photo"
                    ref="photoInput"
                    type="file"
                    class="hidden"
                    @change="updatePhotoPreview"
                >

                <InputLabel for="photo" value="Photo" />

                <!-- Current Profile Photo -->
                <div v-show="! photoPreview" class="mt-2">
                    <img :src="user.profile_photo_url" :alt="user.name" class="rounded-full h-20 w-20 object-cover">
                </div>

                <!-- New Profile Photo Preview -->
                <div v-show="photoPreview" class="mt-2">
                    <span
                        class="block rounded-full w-20 h-20 bg-cover bg-no-repeat bg-center"
                        :style="'background-image: url(\'' + photoPreview + '\');'"
                    />
                </div>

                <SecondaryButton class="mt-2 me-2" type="button" @click.prevent="selectNewPhoto">
                    Select A New Photo
                </SecondaryButton>

                <SecondaryButton
                    v-if="user.profile_photo_path"
                    type="button"
                    class="mt-2"
                    @click.prevent="deletePhoto"
                >
                    Remove Photo
                </SecondaryButton>

                <InputError :message="form.errors.photo" class="mt-2" />
            </div>

            <!-- Name -->
            <div class="col-span-6 sm:col-span-4">
                <InputLabel for="name" value="Name" />
                <TextInput
                    id="name"
                    v-model="form.name"
                    type="text"
                    class="mt-1 block w-full"
                    required
                    autocomplete="name"
                />
                <InputError :message="form.errors.name" class="mt-2" />
            </div>

            <!-- Email -->
            <div class="col-span-6 sm:col-span-4">
                <InputLabel for="email" value="Email" />
                <TextInput
                    id="email"
                    v-model="form.email"
                    type="email"
                    class="mt-1 block w-full"
                    required
                    autocomplete="username"
                />
                <InputError :message="form.errors.email" class="mt-2" />

                <div v-if="$page.props.jetstream.hasEmailVerification && user.email_verified_at === null">
                    <p class="text-sm mt-2 dark:text-white">
                        Your email address is unverified.

                        <Link
                            :href="route('verification.send')"
                            method="post"
                            as="button"
                            class="underline text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:focus:ring-offset-gray-800"
                            @click.prevent="sendEmailVerification"
                        >
                            Click here to re-send the verification email.
                        </Link>
                    </p>

                    <div v-show="verificationLinkSent" class="mt-2 font-medium text-sm text-green-600 dark:text-green-400">
                        A new verification link has been sent to your email address.
                    </div>
                </div>
            </div>
        </template>

        <template #actions>
            <ActionMessage :on="form.recentlySuccessful" class="me-3">
                Saved.
            </ActionMessage>

            <PrimaryButton :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                Save
            </PrimaryButton>
        </template>
    </FormSection>
</template>
