// resources/js/Pages/Profile/Partials/_UpdatePasswordForm.vue
<script setup>
import { ref } from 'vue';
import { useForm } from '@inertiajs/vue3';
import ActionMessage from '@/Components/__ActionMessage.vue';
import FormSection from '@/Components/__FormSection.vue';
import InputError from '@/Components/__InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';

const passwordInput = ref(null);
const currentPasswordInput = ref(null);

const form = useForm({
    current_password: '',
    password: '',
    password_confirmation: '',
});

const updatePassword = () => {
    form.put(route('user-password.update'), {
        errorBag: 'updatePassword',
        preserveScroll: true,
        onSuccess: () => form.reset(),
        onError: () => {
            if (form.errors.password) {
                form.reset('password', 'password_confirmation');
                passwordInput.value.focus();
            }

            if (form.errors.current_password) {
                form.reset('current_password');
                currentPasswordInput.value.focus();
            }
        },
    });
};
</script>

<template>
    <FormSection @submitted="updatePassword">
        <template #title>
            Update Password
        </template>

        <template #description>
            Ensure your account is using a long, random password to stay secure.
        </template>

        <template #form>
            <div class="col-span-6 sm:col-span-4">
                <InputLabel for="current_password" value="Current Password" />
                <TextInput
                    id="current_password"
                    ref="currentPasswordInput"
                    v-model="form.current_password"
                    type="password"
                    class="mt-1 block w-full"
                    autocomplete="current-password"
                />
                <InputError :message="form.errors.current_password" class="mt-2" />
            </div>

            <div class="col-span-6 sm:col-span-4">
                <InputLabel for="password" value="New Password" />
                <TextInput
                    id="password"
                    ref="passwordInput"
                    v-model="form.password"
                    type="password"
                    class="mt-1 block w-full"
                    autocomplete="new-password"
                />
                <InputError :message="form.errors.password" class="mt-2" />
            </div>

            <div class="col-span-6 sm:col-span-4">
                <InputLabel for="password_confirmation" value="Confirm Password" />
                <TextInput
                    id="password_confirmation"
                    v-model="form.password_confirmation"
                    type="password"
                    class="mt-1 block w-full"
                    autocomplete="new-password"
                />
                <InputError :message="form.errors.password_confirmation" class="mt-2" />
            </div>
        </template>

        <template #actions>
            <ActionMessage :on="form.recentlySuccessful" class="me-3">
                Saved.
            </ActionMessage>

            <PrimaryButton :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                Save
            </PrimaryButton>
        </template>
    </FormSection>
</template>

// resources/js/Pages/Profile/Partials/UpdatePasswordForm.svelte
<script>

// /home/dorn/Dev/yatodo-inertia/resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.svelte

    import { t } from 'svelte-i18n';

    import { useForm, page } from '@inertiajs/svelte'; // Ensure proper import

    //
    import FormSection from '@components/Forms/FormSection.svelte';
    import ActionMessage from '@components/Forms/ActionMessage.svelte';

    //
    import Button from '@components/UI/Buttons/Button.svelte';
    import FieldText from '@components/Fields/Text.svelte';
    import FieldPassword from '@components/Fields/Password.svelte';

    let photoInput;
    let photoPreview = null;
    let photoName = null;
    let verificationLinkSent = false;

    //$: user = $page?.props?.user; // Use optional chaining to prevent errors
    $: user = $page?.props?.auth?.user || {};

    // Reactive form object initialization
    const form = useForm({
        current_password: '',
        password: '',
        password_confirmation: '',
    })

    const updatePassword = () => {
        $form.put(route('user-password.update'), {
            errorBag: 'updatePassword',
            preserveScroll: true,
            onSuccess: () => $form.reset(),
            onError: () => {
                if ($form.errors.password) {
                    $form.reset('password', 'password_confirmation');
                    passwordInput.value.focus();
                }

                if ($form.errors.current_password) {
                    $form.reset('current_password');
                    currentPasswordInput.value.focus();
                }
            },
        });
    };

</script>

<FormSection on:submit={updatePassword}>

    <div slot="title">{$t('Update Password')}</div>
    <div slot="description">{$t('Ensure your account is using a long, random password to stay secure.')}</div>

    <div slot="form">
        <FieldPassword form={$form} name="current_password" id="current_password"  label="{$t('Current Password')}"/>
        <FieldPassword form={$form} name="password" id="password"  label="{$t('New Password')}"/>
        <FieldPassword form={$form} name="password_confirmation" id="password_confirmation"  label="{$t('Confirm Password')}"/>
    </div>

    <div slot="actions">
        <ActionMessage on={form.recentlySuccessful}>{$t('Saved')}</ActionMessage>

        <Button
            cssClass="btn-outline-primary"
            type="submit"
            disabled={form.processing}
            aria-label="Save Profile"
        >
            {$t('Save')}
        </Button>
    </div>
</FormSection>
