// resources/js/Pages/API/Partials/ApiTokenManager.svelte
<script>

// resources/js/Pages/API/Partials/ApiTokenManager.svelte

    import { t } from 'svelte-i18n';
    import { ray } from 'node-ray';


    import { useForm, page, router } from "@inertiajs/svelte";

    // Components
    import FormSection from '@components/Forms/FormSection.svelte';
    import ActionMessage from '@components/Forms/ActionMessage.svelte';
    import UserAvatar from '@components/User/Avatar.svelte';
    import Button from '@components/UI/Buttons/Button.svelte';
    import FieldText from '@components/Fields/Text.svelte';
    import FieldCheckbox from '@components/Fields/Checkbox.svelte';
    import FieldSwitch from '@components/Fields/Switch.svelte';
    import SectionBorder from '@components/SectionBorder.svelte'
    import ActionSection from '@components/Forms/ActionSection.svelte';
    import DialogModal from '@components/UI/Modal/Dialog.svelte';

    // Props
    export let tokens = [];
    export let availablePermissions = [];
    export let defaultPermissions = [];

    // Reactive state
    let displayingToken = false;
    let managingPermissionsFor = null;
    let apiTokenBeingDeleted = null;
    let createTokenName = '';
    let selectedPermissions = [...defaultPermissions];
    let updatePermissions = [];
    let formErrors = {};
    let recentlySuccessful = false;
    let processing = false;

    //const createApiTokenForm = useForm({
    $: createApiTokenForm = useForm({
        name: '',
        permissions: defaultPermissions,
    });

    //const updateApiTokenForm = useForm({
    $: updateApiTokenForm = useForm({
        permissions: [],
    });

    const deleteApiTokenForm = useForm({});

    const createApiToken = () => {
        $createApiTokenForm.post(route('api-tokens.store'), {
            preserveScroll: true,
            onSuccess: () => {
                displayingToken = true;
                $createApiTokenForm.reset();
            },
        });
    };

    const manageApiTokenPermissions = (token) => {
        updateApiTokenForm.permissions = token.abilities;
        managingPermissionsFor = token;
    };

    const updateApiToken = () => {
        updateApiTokenForm.put(route('api-tokens.update', managingPermissionsFor), {
            preserveScroll: true,
            preserveState: true,
            onSuccess: () => (managingPermissionsFor = null),
        });
    };

    const confirmApiTokenDeletion = (token) => {
        apiTokenBeingDeleted = token;
    };

    const deleteApiToken = () => {
        deleteApiTokenForm.delete(route('api-tokens.destroy', apiTokenBeingDeleted), {
            preserveScroll: true,
            preserveState: true,
            onSuccess: () => (apiTokenBeingDeleted = null),
        });
    };


</script>


<FormSection on:submit={createApiToken}>
    <div slot="title">{$t('Create API Token')}</div>
    <div slot="description">{$t('API tokens allow third-party services to authenticate with our application on your behalf.')}</div>
    <div slot="form">
        <FieldText 
            form={$createApiTokenForm} 
            name="name" 
            id="name" 
            label="{$t('Name')}" 
        />
        {#if availablePermissions.length > 0}
            <div class="d-flex justify-content-start mt-3">
                {#each availablePermissions as permission}
                    <FieldSwitch form={$createApiTokenForm} name="selectedPermissions">
                        <span class="me-4 ms-0">
                            {permission}
                        </span>
                    </FieldSwitch>
                {/each}
            </div>
        {/if}
    </div>
    <div slot="actions">
        <ActionMessage on={$createApiTokenForm.recentlySuccessful}>{$t('Saved')}</ActionMessage>
        <Button
            cssClass="btn-outline-primary"
            type="submit"
            disabled={$createApiTokenForm.processing}
            aria-label="Save Profile"
        >
            {$t('Save')}
        </Button>
    </div>
</FormSection>


{#if (tokens.length )}
<SectionBorder />
<ActionSection>
    <div slot="title">{$t('Manage API Tokens')}</div>
    <div slot="description">
        {$t('You may delete any of your existing tokens if they are no longer needed.')}
    </div>
    <div slot="content">

        <div class="d-flex flex-column gap-3">
            {#each tokens as token (token.id)}
                <div class="d-flex align-items-center justify-content-between">
                    <div class="text-break text-light">
                        {token.name}
                    </div>
        
                    <div class="d-flex align-items-center ms-2">
                        {#if token.last_used_ago}
                            <div class="small text-secondary">
                                Last used {token.last_used_ago}
                            </div>
                        {/if}
        
                        {#if availablePermissions.length > 0}
                            <button
                                class="btn btn-link btn-sm ms-3 text-secondary p-0"
                                on:click={() => manageApiTokenPermissions(token)}
                            >
                                Permissions
                            </button>
                        {/if}
        
                        <button 
                            class="btn btn-link btn-sm ms-3 text-danger p-0" 
                            on:click={() => confirmApiTokenDeletion(token)}
                        >
                            Delete
                        </button>
                    </div>
                </div>
            {/each}
        </div>
    </div>  
</ActionSection>
{/if}



<!-- Token Value Modal -->
<DialogModal bind:show={displayingToken} on:close={() => displayingToken = false}>
    <span slot="title">
        {$t('API Token')}
    </span>

    <div slot="content">
        <div>
            {$t('Please copy your new API token. For your security, it won\'t be shown again.')}
        </div>

        {#if $page.props.jetstream?.flash?.token}
            <div class="mt-4 bg-gray-100 dark:bg-gray-900 px-4 py-2 rounded font-mono text-sm text-gray-500 break-all">
                {$page.props.jetstream.flash.token}
            </div>
        {/if}
    </div>

    <div slot="footer">
        <Button 
            cssClass="btn-secondary" 
            on:click={() => displayingToken = false}
        >
            {$t('Close')}
        </Button>
    </div>
</DialogModal>

<!-- API Token Permissions Modal -->
<DialogModal 
    bind:show={managingPermissionsFor} 
    on:close={() => managingPermissionsFor = null}
>
    <span slot="title">
        {$t('API Token Permissions')}
    </span>

    <div slot="content">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            {#each availablePermissions as permission}
                <FieldSwitch 
                    form={$updateApiTokenForm} 
                    name="permissions" 
                    value={permission}
                >
                    <span class="ms-2 text-sm text-gray-600 dark:text-gray-400">
                        {permission}
                    </span>
                </FieldSwitch>
            {/each}
        </div>
    </div>

    <div slot="footer">
        <Button 
            cssClass="btn-secondary" 
            on:click={() => managingPermissionsFor = null}
        >
            {$t('Cancel')}
        </Button>

        <Button
            cssClass="btn-primary ms-3"
            disabled={$updateApiTokenForm.processing}
            on:click={updateApiToken}
        >
            {$t('Save')}
        </Button>
    </div>
</DialogModal>

<!-- Delete Token Confirmation Modal -->
<DialogModal 
    bind:show={apiTokenBeingDeleted} 
    on:close={() => apiTokenBeingDeleted = null}
>
    <span slot="title">
        {$t('Delete API Token')}
    </span>

    <div slot="content">
        {$t('Are you sure you would like to delete this API token?')}
    </div>

    <div slot="footer">
        <Button 
            cssClass="btn-secondary" 
            on:click={() => apiTokenBeingDeleted = null}
        >
            {$t('Cancel')}
        </Button>

        <Button
            cssClass="btn-danger ms-3"
            disabled={$deleteApiTokenForm.processing}
            on:click={deleteApiToken}
        >
            {$t('Delete')}
        </Button>
    </div>
</DialogModal>

// resources/js/Pages/API/Partials/ApiTokenManager.vue
<script setup>
import { ref } from 'vue';
import { useForm } from '@inertiajs/vue3';
import ActionMessage from '@/Components/__ActionMessage.vue';
import ActionSection from '@/Components/__ActionSection.vue';
import Checkbox from '@/Components/Checkbox.vue';
import ConfirmationModal from '@/Components/ConfirmationModal.vue';
import DangerButton from '@/Components/DangerButton.vue';
import DialogModal from '@/Components/__DialogModal.vue';
import FormSection from '@/Components/__FormSection.vue';
import InputError from '@/Components/__InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import SecondaryButton from '@/Components/SecondaryButton.vue';
import SectionBorder from '@/Components/SectionBorder.vue';
import TextInput from '@/Components/TextInput.vue';

const props = defineProps({
    tokens: Array,
    availablePermissions: Array,
    defaultPermissions: Array,
});

const createApiTokenForm = useForm({
    name: '',
    permissions: props.defaultPermissions,
});

const updateApiTokenForm = useForm({
    permissions: [],
});

const deleteApiTokenForm = useForm({});

const displayingToken = ref(false);
const managingPermissionsFor = ref(null);
const apiTokenBeingDeleted = ref(null);

const createApiToken = () => {
    createApiTokenForm.post(route('api-tokens.store'), {
        preserveScroll: true,
        onSuccess: () => {
            displayingToken.value = true;
            createApiTokenForm.reset();
        },
    });
};

const manageApiTokenPermissions = (token) => {
    updateApiTokenForm.permissions = token.abilities;
    managingPermissionsFor.value = token;
};

const updateApiToken = () => {
    updateApiTokenForm.put(route('api-tokens.update', managingPermissionsFor.value), {
        preserveScroll: true,
        preserveState: true,
        onSuccess: () => (managingPermissionsFor.value = null),
    });
};

const confirmApiTokenDeletion = (token) => {
    apiTokenBeingDeleted.value = token;
};

const deleteApiToken = () => {
    deleteApiTokenForm.delete(route('api-tokens.destroy', apiTokenBeingDeleted.value), {
        preserveScroll: true,
        preserveState: true,
        onSuccess: () => (apiTokenBeingDeleted.value = null),
    });
};
</script>

<template>
    <div>
        <!-- Generate API Token -->
        <FormSection @submitted="createApiToken">
            <template #title>
                Create API Token
            </template>

            <template #description>
                API tokens allow third-party services to authenticate with our application on your behalf.
            </template>

            <template #form>
                <!-- Token Name -->
                <div class="col-span-6 sm:col-span-4">
                    <InputLabel for="name" value="Name" />
                    <TextInput
                        id="name"
                        v-model="createApiTokenForm.name"
                        type="text"
                        class="mt-1 block w-full"
                        autofocus
                    />
                    <InputError :message="createApiTokenForm.errors.name" class="mt-2" />
                </div>

                <!-- Token Permissions -->
                <div v-if="availablePermissions.length > 0" class="col-span-6">
                    <InputLabel for="permissions" value="Permissions" />

                    <div class="mt-2 grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div v-for="permission in availablePermissions" :key="permission">
                            <label class="flex items-center">
                                <Checkbox v-model:checked="createApiTokenForm.permissions" :value="permission" />
                                <span class="ms-2 text-sm text-gray-600 dark:text-gray-400">{{ permission }}</span>
                            </label>
                        </div>
                    </div>
                </div>
            </template>

            <template #actions>
                <ActionMessage :on="createApiTokenForm.recentlySuccessful" class="me-3">
                    Created.
                </ActionMessage>

                <PrimaryButton :class="{ 'opacity-25': createApiTokenForm.processing }" :disabled="createApiTokenForm.processing">
                    Create
                </PrimaryButton>
            </template>
        </FormSection>

        <div v-if="tokens.length > 0">
            <SectionBorder />

            <!-- Manage API Tokens -->
            <div class="mt-10 sm:mt-0">
                <ActionSection>
                    <template #title>
                        Manage API Tokens
                    </template>

                    <template #description>
                        You may delete any of your existing tokens if they are no longer needed.
                    </template>

                    <!-- API Token List -->
                    <template #content>
                        <div class="space-y-6">
                            <div v-for="token in tokens" :key="token.id" class="flex items-center justify-between">
                                <div class="break-all dark:text-white">
                                    {{ token.name }}
                                </div>

                                <div class="flex items-center ms-2">
                                    <div v-if="token.last_used_ago" class="text-sm text-gray-400">
                                        Last used {{ token.last_used_ago }}
                                    </div>

                                    <button
                                        v-if="availablePermissions.length > 0"
                                        class="cursor-pointer ms-6 text-sm text-gray-400 underline"
                                        @click="manageApiTokenPermissions(token)"
                                    >
                                        Permissions
                                    </button>

                                    <button class="cursor-pointer ms-6 text-sm text-red-500" @click="confirmApiTokenDeletion(token)">
                                        Delete
                                    </button>
                                </div>
                            </div>
                        </div>
                    </template>
                </ActionSection>
            </div>
        </div>

        <!-- Token Value Modal -->
        <DialogModal :show="displayingToken" @close="displayingToken = false">
            <template #title>
                API Token
            </template>

            <template #content>
                <div>
                    Please copy your new API token. For your security, it won't be shown again.
                </div>

                <div v-if="$page.props.jetstream.flash.token" class="mt-4 bg-gray-100 dark:bg-gray-900 px-4 py-2 rounded font-mono text-sm text-gray-500 break-all">
                    {{ $page.props.jetstream.flash.token }}
                </div>
            </template>

            <template #footer>
                <SecondaryButton @click="displayingToken = false">
                    Close
                </SecondaryButton>
            </template>
        </DialogModal>

        <!-- API Token Permissions Modal -->
        <DialogModal :show="managingPermissionsFor != null" @close="managingPermissionsFor = null">
            <template #title>
                API Token Permissions
            </template>

            <template #content>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div v-for="permission in availablePermissions" :key="permission">
                        <label class="flex items-center">
                            <Checkbox v-model:checked="updateApiTokenForm.permissions" :value="permission" />
                            <span class="ms-2 text-sm text-gray-600 dark:text-gray-400">{{ permission }}</span>
                        </label>
                    </div>
                </div>
            </template>

            <template #footer>
                <SecondaryButton @click="managingPermissionsFor = null">
                    Cancel
                </SecondaryButton>

                <PrimaryButton
                    class="ms-3"
                    :class="{ 'opacity-25': updateApiTokenForm.processing }"
                    :disabled="updateApiTokenForm.processing"
                    @click="updateApiToken"
                >
                    Save
                </PrimaryButton>
            </template>
        </DialogModal>

        <!-- Delete Token Confirmation Modal -->
        <ConfirmationModal :show="apiTokenBeingDeleted != null" @close="apiTokenBeingDeleted = null">
            <template #title>
                Delete API Token
            </template>

            <template #content>
                Are you sure you would like to delete this API token?
            </template>

            <template #footer>
                <SecondaryButton @click="apiTokenBeingDeleted = null">
                    Cancel
                </SecondaryButton>

                <DangerButton
                    class="ms-3"
                    :class="{ 'opacity-25': deleteApiTokenForm.processing }"
                    :disabled="deleteApiTokenForm.processing"
                    @click="deleteApiToken"
                >
                    Delete
                </DangerButton>
            </template>
        </ConfirmationModal>
    </div>
</template>
