// resources/js/Pages/API/Index.vue
<script setup>
import ApiTokenManager from '@/Pages/API/Partials/__ApiTokenManager.vue';
import AppLayout from '@/Layouts/__AppLayout.vue';

defineProps({
    tokens: Array,
    availablePermissions: Array,
    defaultPermissions: Array,
});
</script>

<template>
    <AppLayout title="API Tokens">
        <template #header>
            <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
                API Tokens
            </h2>
        </template>

        <div>
            <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
                <ApiTokenManager
                    :tokens="tokens"
                    :available-permissions="availablePermissions"
                    :default-permissions="defaultPermissions"
                />
            </div>
        </div>
    </AppLayout>
</template>

// resources/js/Pages/API/Index.svelte
<!-- resources/js/Pages/Dashboard.svelte -->
<script>


    import App from "@layouts/App.svelte";
    import ApiTokenManager from '@pages/API/Partials/ApiTokenManager.svelte';
    
    export let tokens = [];
    export let availablePermissions = [];
    export let defaultPermissions = [];

</script>

<svelte:head>
    <title>API</title>
</svelte:head>

<App>

    <!-- This content will be passed to the named "hero" slot -->
    <div slot="hero" class="hero-contents">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            <i class="bi bi-braces-asterisk me-2"></i> API
        </h2>
        <!-- <p>Additional content here, like a description or other elements.</p> -->
    </div>

    <div class="page-content container py-5">
        <ApiTokenManager
            {tokens}
            {availablePermissions}
            {defaultPermissions}
        />
    </div>

</App>
